# Generated by Django 4.2.3 on 2023-08-27 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Curso',
            new_name='Aula',
        ),
        migrations.RenameModel(
            old_name='Entregable',
            new_name='Desafio',
        ),
        migrations.RenameModel(
            old_name='Profesor',
            new_name='Tutor',
        ),
    ]
